spring:
  application:
    name: spring-boot-sample
  gdy:
    roy:
      name: guoj
      age : 66
  # redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
    lettuce:
      pool:
        max-idle:  10
        max-active: 200
        max-wait: -1ms
        min-idle: 10
guo1:
  name1: 123
server:
  port: 8099